# Change these first
owner: adamtem # Your GitHub organization or username, where this repository lives
repo: adamtem.github.io # The name of this repository

sites:
  - name: WILLADAM BOT
    url: http://dec28c28-198d-4d24-b83c-f4aa20d662bd-00-1v5umdg3igut.spock.replit.dev/
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: willadam bot yippee
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/adamtem/adamtem.github.io

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
